using System.Net;
using DukkanPilot.IntegrationTests.Infrastructure;
using Microsoft.EntityFrameworkCore;
namespace DukkanPilot.IntegrationTests.TableService;
public sealed class TableAuthorizationTests
{
 [Fact] public async Task Staff_views_own_list_and_qr_but_is_forbidden_from_write_actions(){using var f=new DukkanPilotWebApplicationFactory();await f.InitializeAsync();using var c=TestClaims.CreateClient(f,TestUser.TenantAStaff);var d=f.Data;var i=await c.GetAsync("/Business/Tables");Assert.Equal(HttpStatusCode.OK,i.StatusCode);Assert.Contains(d.TenantATable1Label,await i.Content.ReadAsStringAsync());Assert.Equal(HttpStatusCode.OK,(await c.GetAsync($"/Business/Tables/Qr/{d.TenantATable1Id}")).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await c.GetAsync($"/Business/Tables/Qr/{d.TenantBTable1Id}")).StatusCode);Denied(await c.GetAsync("/Business/Tables/Create"));var t=await AntiforgeryHelper.GetAsync(c,"/Business/Tables");var post=new HttpRequestMessage(HttpMethod.Post,"/Business/Tables/Create"){Content=new FormUrlEncodedContent(new Dictionary<string,string>{{"TableLabel","No"},{"DisplayOrder","9"}})};AntiforgeryHelper.Add(post,t);Denied(await c.SendAsync(post));var toggle=new HttpRequestMessage(HttpMethod.Post,$"/Business/Tables/Toggle/{d.TenantATable1Id}");AntiforgeryHelper.Add(toggle,t);Denied(await c.SendAsync(toggle));Assert.True(await f.DbAsync(x=>x.BusinessTables.Where(z=>z.Id==d.TenantATable1Id).Select(z=>z.IsActive).SingleAsync()));}
 [Fact] public async Task Owner_manages_own_table_but_not_foreign_table(){using var f=new DukkanPilotWebApplicationFactory();await f.InitializeAsync();using var c=TestClaims.CreateClient(f,TestUser.TenantAOwner);var d=f.Data;var t=await AntiforgeryHelper.GetAsync(c,$"/Business/Tables/Edit/{d.TenantATable1Id}");var e=new HttpRequestMessage(HttpMethod.Post,$"/Business/Tables/Edit/{d.TenantATable1Id}"){Content=new FormUrlEncodedContent(new Dictionary<string,string>{{"Id",d.TenantATable1Id.ToString()},{"TableLabel","A Edited"},{"DisplayOrder","1"},{"IsActive","true"}})};AntiforgeryHelper.Add(e,t);Assert.Equal(HttpStatusCode.Found,(await c.SendAsync(e)).StatusCode);t=await AntiforgeryHelper.GetAsync(c,"/Business/Tables");var q=new HttpRequestMessage(HttpMethod.Post,$"/Business/Tables/Toggle/{d.TenantATable1Id}");AntiforgeryHelper.Add(q,t);Assert.Equal(HttpStatusCode.Found,(await c.SendAsync(q)).StatusCode);var foreign=new HttpRequestMessage(HttpMethod.Post,$"/Business/Tables/Toggle/{d.TenantBTable1Id}");AntiforgeryHelper.Add(foreign,t);Assert.Equal(HttpStatusCode.NotFound,(await c.SendAsync(foreign)).StatusCode);var x=await f.DbAsync(async db=>new{A=await db.BusinessTables.SingleAsync(z=>z.Id==d.TenantATable1Id),B=await db.BusinessTables.SingleAsync(z=>z.Id==d.TenantBTable1Id)});Assert.Equal("A Edited",x.A.TableLabel);Assert.False(x.A.IsActive);Assert.Equal(d.TenantBTable1Label,x.B.TableLabel);}
 static void Denied(HttpResponseMessage r){Assert.Equal(HttpStatusCode.Found,r.StatusCode);Assert.Contains("/Account/AccessDenied",r.Headers.Location!.OriginalString);Assert.DoesNotContain("/Account/Login",r.Headers.Location!.OriginalString);}
}
